Vagrant.configure('2') do |config|

    config.vm.hostname = 'vetsec-wg'
    config.vm.box = 'bento/ubuntu-18.04'
    config.vm.synced_folder './', '/vagrant'

    config.ssh.username = 'vagrant'

    config.vm.provider :virtualbox do |vb|
        vb.name = 'vetsec-wargame'
        vb.customize ['modifyvm', :id, '--memory', '768', '--cpus', '2']
        vb.gui = false
    end

    config.vm.provision :shell do |shell|
        shell.privileged = false
        shell.inline = <<-SHELL
            sudo apt-get -y install gdb
            git clone https://github.com/longld/peda.git ~/peda
            echo "source ~/peda/peda.py" >> ~/.gdbinit
        SHELL
    end
end
